/**
 * Adopter — generate pre-filled BuildPact artifacts from scan results.
 * Used by `buildpact adopt` to onboard existing (brownfield) projects.
 * @module foundation/adopter
 */

import { mkdir, readFile, writeFile, copyFile, readdir, access } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ok, err } from '../contracts/errors.js'
import type { Result } from '../contracts/errors.js'
import type { SupportedLanguage } from '../contracts/i18n.js'
import type { IdeId } from './installer.js'
import { AuditLogger } from './audit.js'
import { CURRENT_SCHEMA_VERSION } from './version-guard.js'
import type { ScanResult } from './scanner.js'

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CLI_VERSION = '0.1.0-alpha.5'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AdoptOptions {
  projectDir: string
  language: SupportedLanguage
  scan: ScanResult
  mergeExisting: boolean
  ides: IdeId[]
  experienceLevel: 'beginner' | 'intermediate' | 'expert'
  installSquad: boolean
  domain: string
}

export interface AdoptResult {
  created: string[]
  modified: string[]
  skipped: string[]
}

// ---------------------------------------------------------------------------
// Template helpers
// ---------------------------------------------------------------------------

function resolveTemplatesDir(): string {
  try {
    const __filename = fileURLToPath(import.meta.url)
    const __dirname = dirname(__filename)
    // tsdown may inline into dist/cli/index.mjs (2 levels up) or a flat dist/ chunk (1 level up)
    const oneLevelUp = join(__dirname, '..', 'templates')
    if (existsSync(oneLevelUp)) return oneLevelUp
    return join(__dirname, '..', '..', 'templates')
  } catch {
    return join(process.cwd(), 'templates')
  }
}

function interpolate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => vars[key] ?? `{{${key}}}`)
}

async function copyDir(src: string, dest: string): Promise<void> {
  await mkdir(dest, { recursive: true })
  const entries = await readdir(src, { withFileTypes: true })
  for (const entry of entries) {
    const srcPath = join(src, entry.name)
    const destPath = join(dest, entry.name)
    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath)
    } else {
      await copyFile(srcPath, destPath)
    }
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

// ---------------------------------------------------------------------------
// Constitution generation from scan
// ---------------------------------------------------------------------------

/** Generate a pre-filled constitution.md from scan results. */
export function generateConstitutionFromScan(scan: ScanResult, projectName: string): string {
  const createdAt = new Date().toISOString().slice(0, 10)
  const sections: string[] = []

  sections.push(`# Project Constitution — ${projectName}`)
  sections.push('')
  sections.push(`> Auto-generated by \`buildpact adopt\` on ${createdAt}.`)
  sections.push('> Review and adjust these rules — they were inferred from your existing project.')
  sections.push('')
  sections.push('---')
  sections.push('')

  // Coding Standards
  sections.push('## Immutable Principles')
  sections.push('')
  sections.push('### Coding Standards')

  if (scan.languages.length > 0) {
    sections.push(`- Primary language(s): ${scan.languages.join(', ')}`)
  }

  for (const linter of scan.linters) {
    sections.push(`- ${linter.tool} enforced (config: ${linter.configFile})`)
    for (const rule of linter.extractedRules) {
      sections.push(`  - ${rule}`)
    }
  }

  if (scan.linters.length === 0) {
    sections.push('- No linter detected — consider adding one')
  }

  sections.push('- Spec before code — no implementation begins without a reviewed specification')
  sections.push('- Atomic commits — one commit per completed task')
  sections.push('')

  // Compliance
  sections.push('### Compliance Requirements')
  sections.push('- None detected — add project-specific compliance requirements here')
  sections.push('')

  // Architectural Constraints
  sections.push('### Architectural Constraints')

  for (const pkg of scan.packageManagers) {
    sections.push(`- Package manager: ${pkg.name} (${pkg.configFile})`)
    if (pkg.version) sections.push(`  - Project version: ${pkg.version}`)
  }

  sections.push('- No circular dependencies between modules')
  sections.push('')

  // Quality Gates
  sections.push('### Quality Gates')

  for (const ci of scan.ci) {
    const gates = ci.qualityGates.length > 0 ? ` (gates: ${ci.qualityGates.join(', ')})` : ''
    sections.push(`- CI: ${ci.platform}${gates}`)
  }

  sections.push('- All tests must pass before any commit')
  sections.push('')

  // Domain
  sections.push('## Domain-Specific Rules')
  sections.push('- None by default — add Squad-specific rules here')
  sections.push('')

  // Version History
  sections.push('---')
  sections.push('')
  sections.push('## Version History')
  sections.push('| Date | Change | Reason |')
  sections.push('|------|--------|--------|')
  sections.push(`| ${createdAt} | Initial creation | Project adopted via \`buildpact adopt\` |`)
  sections.push('')

  return sections.join('\n')
}

/** Generate a pre-filled project-context.md from scan results. */
export function generateContextFromScan(
  scan: ScanResult,
  projectName: string,
  language: SupportedLanguage,
  experienceLevel: string,
  activeSquad: string,
): string {
  const createdAt = new Date().toISOString().slice(0, 10)
  const sections: string[] = []

  // Frontmatter
  sections.push('---')
  sections.push(`project_name: "${projectName}"`)
  sections.push(`created_at: "${createdAt}"`)
  sections.push(`language: "${language}"`)
  sections.push(`document_language: "en"`)
  sections.push(`experience_level: "${experienceLevel}"`)
  sections.push(`active_squad: "${activeSquad}"`)
  sections.push(`active_model_profile: "balanced"`)
  sections.push(`workflow_phase: "adopted"`)
  sections.push('---')
  sections.push('')

  sections.push(`# ${projectName} — Project Context`)
  sections.push('')
  sections.push('> Auto-generated by `buildpact adopt`. Update this file with project-specific details.')
  sections.push('')
  sections.push('---')
  sections.push('')

  // Tech stack
  sections.push('## Technology Stack')
  sections.push('')

  if (scan.languages.length > 0) {
    sections.push(`- **Languages:** ${scan.languages.join(', ')}`)
  }
  for (const pkg of scan.packageManagers) {
    sections.push(`- **Package manager:** ${pkg.name} (${pkg.configFile})`)
  }
  for (const linter of scan.linters) {
    sections.push(`- **Linter/formatter:** ${linter.tool} (${linter.configFile})`)
  }
  for (const ci of scan.ci) {
    sections.push(`- **CI/CD:** ${ci.platform} (${ci.configFile})`)
  }
  if (scan.git) {
    sections.push(`- **Git:** ${scan.git.commitCount} commits, ${scan.git.contributorCount} contributor(s)`)
  }

  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## What is this project?')
  sections.push('')
  sections.push('<!-- Describe your project here -->')
  sections.push('')
  sections.push('---')
  sections.push('')
  sections.push('## Current State')
  sections.push('')
  sections.push('- Next action: Run `buildpact specify` to begin specification pipeline')
  sections.push('')

  return sections.join('\n')
}

// ---------------------------------------------------------------------------
// Config generation
// ---------------------------------------------------------------------------

function generateConfigYaml(
  projectName: string,
  language: SupportedLanguage,
  experienceLevel: string,
  activeSquad: string,
): string {
  const createdAt = new Date().toISOString().slice(0, 10)
  return [
    '# BuildPact project configuration',
    '# Generated by: buildpact adopt',
    '',
    `buildpact_schema: ${CURRENT_SCHEMA_VERSION}`,
    `created_by_cli: "${CLI_VERSION}"`,
    `last_upgraded_by_cli: "${CLI_VERSION}"`,
    '',
    `project_name: "${projectName}"`,
    `language: "${language}"`,
    `experience_level: "${experienceLevel}"`,
    `active_squad: "${activeSquad}"`,
    `active_model_profile: "balanced"`,
    `created_at: "${createdAt}"`,
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Execute adoption: generate and write all BuildPact artifacts.
 * Respects mergeExisting flag — if true, skips files that already exist.
 */
export async function adopt(options: AdoptOptions): Promise<Result<AdoptResult>> {
  const {
    projectDir,
    language,
    scan,
    mergeExisting,
    ides,
    experienceLevel,
    installSquad,
    domain,
  } = options

  const projectName = scan.projectName
  const activeSquad = installSquad ? 'software' : 'none'
  const buildpactDir = join(projectDir, '.buildpact')
  const auditDir = join(buildpactDir, 'audit')
  const logger = new AuditLogger(join(auditDir, 'adopt.jsonl'))
  const templatesDir = resolveTemplatesDir()

  const created: string[] = []
  const modified: string[] = []
  const skipped: string[] = []

  try {
    await logger.log({ action: 'adopt.start', agent: 'adopter', files: [], outcome: 'success' })
    await mkdir(auditDir, { recursive: true })

    // 1. Constitution
    const constitutionPath = join(buildpactDir, 'constitution.md')
    if (mergeExisting && await fileExists(constitutionPath)) {
      skipped.push('.buildpact/constitution.md')
    } else {
      const content = generateConstitutionFromScan(scan, projectName)
      await writeFile(constitutionPath, content, 'utf-8')
      created.push('.buildpact/constitution.md')
    }

    // 2. Config
    const configPath = join(buildpactDir, 'config.yaml')
    if (mergeExisting && await fileExists(configPath)) {
      // Add schema fields if missing
      let existing = await readFile(configPath, 'utf-8')
      if (!existing.includes('buildpact_schema:')) {
        const schemaBlock = [
          `buildpact_schema: ${CURRENT_SCHEMA_VERSION}`,
          `created_by_cli: "${CLI_VERSION}"`,
          `last_upgraded_by_cli: "${CLI_VERSION}"`,
          '',
        ].join('\n')
        const lines = existing.split('\n')
        const insertIdx = lines.findIndex(l => !l.startsWith('#') && l.trim().length > 0)
        if (insertIdx >= 0) {
          lines.splice(insertIdx, 0, schemaBlock)
        } else {
          lines.unshift(schemaBlock)
        }
        existing = lines.join('\n')
        await writeFile(configPath, existing, 'utf-8')
        modified.push('.buildpact/config.yaml')
      } else {
        skipped.push('.buildpact/config.yaml')
      }
    } else {
      const content = generateConfigYaml(projectName, language, experienceLevel, activeSquad)
      await writeFile(configPath, content, 'utf-8')
      created.push('.buildpact/config.yaml')
    }

    // 3. Project context
    const contextPath = join(buildpactDir, 'project-context.md')
    if (mergeExisting && await fileExists(contextPath)) {
      skipped.push('.buildpact/project-context.md')
    } else {
      const content = generateContextFromScan(scan, projectName, language, experienceLevel, activeSquad)
      await writeFile(contextPath, content, 'utf-8')
      created.push('.buildpact/project-context.md')
    }

    // 4. Profiles
    const profilesDest = join(buildpactDir, 'profiles')
    if (mergeExisting && await fileExists(profilesDest)) {
      skipped.push('.buildpact/profiles')
    } else {
      await copyDir(join(templatesDir, 'profiles'), profilesDest)
      created.push('.buildpact/profiles')
    }

    // 5. IDE configs — always install BuildPact slash commands even if IDE is already configured,
    //    because having .claude/commands doesn't mean .claude/commands/bp/ exists.
    for (const ide of ides) {
      await installIdeConfig(ide, projectDir, templatesDir)
      created.push(`IDE: ${ide}`)
    }

    // 6. Squad
    if (installSquad) {
      const squadDest = join(buildpactDir, 'squads', 'software')
      if (mergeExisting && await fileExists(squadDest)) {
        skipped.push('.buildpact/squads/software')
      } else {
        await copyDir(join(templatesDir, 'squads', 'software'), squadDest)
        created.push('.buildpact/squads/software')
      }
    }

    // 7. DECISIONS.md and STATUS.md (skip if exist)
    for (const file of ['DECISIONS.md', 'STATUS.md']) {
      const filePath = join(projectDir, file)
      if (await fileExists(filePath)) {
        skipped.push(file)
      } else {
        const vars: Record<string, string> = {
          project_name: projectName,
          language,
          experience_level: experienceLevel,
          active_squad: activeSquad,
          created_at: new Date().toISOString().slice(0, 10),
        }
        const template = await readFile(join(templatesDir, file), 'utf-8')
        await writeFile(filePath, interpolate(template, vars), 'utf-8')
        created.push(file)
      }
    }

    await logger.log({
      action: 'adopt.complete',
      agent: 'adopter',
      files: [...created, ...modified],
      outcome: 'success',
    })

    return ok({ created, modified, skipped })
  } catch (cause) {
    try {
      await logger.log({ action: 'adopt.error', agent: 'adopter', files: [], outcome: 'failure', error: String(cause) })
    } catch { /* swallow */ }
    return err({
      code: 'ADOPT_FAILED',
      i18nKey: 'error.adopt.failed',
      cause,
    })
  }
}

// ---------------------------------------------------------------------------
// IDE config (simplified from installer.ts)
// ---------------------------------------------------------------------------

async function installIdeConfig(ide: IdeId, projectDir: string, tplDir: string): Promise<void> {
  switch (ide) {
    case 'claude-code': {
      const commandsDir = join(projectDir, '.claude', 'commands', 'bp')
      await mkdir(commandsDir, { recursive: true })
      await copyDir(join(tplDir, 'commands'), commandsDir)
      const claudeMd = join(projectDir, 'CLAUDE.md')
      if (!await fileExists(claudeMd)) {
        await writeFile(
          claudeMd,
          '# CLAUDE.md — BuildPact Project\n\nSee .buildpact/constitution.md for project rules.\n\nBuildPact slash commands are available as /bp:specify, /bp:plan, /bp:execute, /bp:verify, /bp:quick, /bp:constitution, /bp:squad, /bp:optimize, /bp:doctor.\n',
          'utf-8',
        )
      }
      break
    }
    case 'cursor': {
      await mkdir(join(projectDir, '.cursor', 'rules'), { recursive: true })
      const cursorRules = join(projectDir, '.cursorrules')
      if (!await fileExists(cursorRules)) {
        await writeFile(cursorRules, '# BuildPact — Cursor Rules\n\nSee .buildpact/constitution.md for project rules.\n', 'utf-8')
      }
      break
    }
    case 'gemini': {
      await mkdir(join(projectDir, '.gemini'), { recursive: true })
      break
    }
    case 'codex': {
      await mkdir(join(projectDir, '.codex'), { recursive: true })
      break
    }
  }
}
