/**
 * Diagnose command handler — reads or generates .buildpact/diagnostic-report.md
 * and presents analysis with next-step recommendations.
 *
 * Flow:
 * 1. Check if diagnostic-report.md exists (generated by `buildpact adopt`)
 * 2. If not, run scanner + diagnostician to generate it
 * 3. If yes but stale (>24h), regenerate
 * 4. Present summary + recommendations + suggested next action
 *
 * @module commands/diagnose
 */

import * as clack from '@clack/prompts'
import { readFileSync } from 'node:fs'
import { readFile, writeFile, stat } from 'node:fs/promises'
import { join } from 'node:path'
import { createI18n } from '../../foundation/i18n.js'
import { scanProject } from '../../foundation/scanner.js'
import { diagnoseProject, formatDiagnosticReport } from '../../foundation/diagnostician.js'
import { AuditLogger } from '../../foundation/audit.js'
import { ok } from '../../contracts/errors.js'
import type { Result } from '../../contracts/errors.js'
import type { SupportedLanguage } from '../../contracts/i18n.js'

/** Read language from config.yaml (sync, with fallback) */
function readLanguage(projectDir: string): SupportedLanguage {
  try {
    const content = readFileSync(join(projectDir, '.buildpact', 'config.yaml'), 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (trimmed.startsWith('language:')) {
        const value = trimmed.slice('language:'.length).trim().replace(/^["']|["']$/g, '')
        if (value === 'pt-br' || value === 'en') return value
      }
    }
  } catch { /* default */ }
  return 'en'
}

/** Check if a file exists and how old it is */
async function fileAge(path: string): Promise<number | null> {
  try {
    const s = await stat(path)
    return Date.now() - s.mtimeMs
  } catch {
    return null
  }
}

const ONE_DAY_MS = 24 * 60 * 60 * 1000

export async function runDiagnose(_args: string[]): Promise<Result<void>> {
  const projectDir = process.cwd()
  const lang = readLanguage(projectDir)
  const i18n = createI18n(lang)
  const audit = new AuditLogger(join(projectDir, '.buildpact', 'audit', 'cli.jsonl'))
  const reportPath = join(projectDir, '.buildpact', 'diagnostic-report.md')

  clack.intro(i18n.t('cli.diagnose.welcome'))

  const spinner = clack.spinner()

  // Check if report already exists (from adopt or previous diagnose)
  const age = await fileAge(reportPath)
  let needsRegeneration = true

  if (age !== null && age < ONE_DAY_MS) {
    clack.log.info(i18n.t('cli.diagnose.report_exists'))
    needsRegeneration = false
  }

  if (needsRegeneration) {
    // Generate fresh diagnostic
    spinner.start(i18n.t('cli.diagnose.scanning'))
    const scan = await scanProject(projectDir)
    spinner.stop(i18n.t('cli.diagnose.scan_done'))

    spinner.start(i18n.t('cli.diagnose.analyzing'))
    const diagnostic = await diagnoseProject(projectDir, scan)
    const reportContent = formatDiagnosticReport(diagnostic, lang)
    await writeFile(reportPath, reportContent, 'utf-8')
    spinner.stop(i18n.t('cli.diagnose.analysis_done'))
  }

  // Read the report
  let report: string
  try {
    report = await readFile(reportPath, 'utf-8')
  } catch {
    clack.log.error(i18n.t('cli.diagnose.report_read_failed'))
    return ok(undefined)
  }

  // Parse key metrics from the report
  const docsMatch = report.match(/Files checked:\s*(\d+)|Arquivos verificados:\s*(\d+)/)
  const docsCount = docsMatch ? parseInt(docsMatch[1] ?? docsMatch[2] ?? '0', 10) : 0

  const phasesMatch = report.match(/(\d+)\/(\d+)\s*(?:phases?|fases?)/)
  const phasesDone = phasesMatch ? parseInt(phasesMatch[1]!, 10) : 0
  const phasesTotal = phasesMatch ? parseInt(phasesMatch[2]!, 10) : 0

  const locMatch = report.match(/([\d,]+)\s*(?:LOC|lines)/)
  const loc = locMatch ? locMatch[1]! : '0'

  // Extract recommendations (lines starting with number + period)
  const recLines = report.split('\n').filter(l => /^\d+\.\s/.test(l.trim())).slice(0, 5)

  // Show summary
  const summaryLines = [
    `${i18n.t('cli.diagnose.docs_found', { count: String(docsCount) })}`,
    ...(phasesTotal > 0 ? [`${i18n.t('cli.diagnose.phases', { done: String(phasesDone), total: String(phasesTotal) })}`] : []),
    `${loc} LOC`,
  ]
  clack.note(summaryLines.join('\n'), i18n.t('cli.diagnose.summary_title'))

  if (recLines.length > 0) {
    clack.note(recLines.join('\n'), i18n.t('cli.diagnose.recommendations_title'))
  }

  clack.log.success(i18n.t('cli.diagnose.report_saved', { path: '.buildpact/diagnostic-report.md' }))

  // Suggest next step
  const hasPrd = report.toLowerCase().includes('prd') || report.toLowerCase().includes('requirements')
  const hasSpecs = report.includes('spec.md') || report.includes('specs/')
  const hasPlans = report.includes('wave-') || report.includes('plans/')

  if (hasPlans && phasesDone < phasesTotal) {
    clack.log.info(i18n.t('cli.diagnose.next_continue'))
  } else if (hasPrd || hasSpecs) {
    clack.log.info(i18n.t('cli.diagnose.next_plan'))
  } else {
    clack.log.info(i18n.t('cli.diagnose.next_specify'))
  }

  clack.outro(i18n.t('cli.diagnose.outro'))

  await audit.log({ action: 'diagnose.complete', agent: 'cli', files: [reportPath], outcome: 'success' })
  return ok(undefined)
}
