/**
 * Squad Lock — version pinning with content hash integrity.
 * Creates and manages `.buildpact/squad-lock.yaml` to track installed
 * squad versions and detect file drift.
 * @see Epic 16.1: Squad Version Pinning & Lockfile
 */

import { readFile, writeFile, readdir, stat } from 'node:fs/promises'
import { join, relative } from 'node:path'
import { createHash } from 'node:crypto'
import { ok, err, ERROR_CODES } from '../contracts/errors.js'
import type { Result } from '../contracts/errors.js'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A single locked squad entry */
export interface LockedSquad {
  /** Squad name */
  name: string
  /** Semantic version from squad.yaml */
  version: string
  /** SHA-256 hash of all squad files concatenated (sorted by path) */
  contentHash: string
  /** ISO 8601 timestamp when locked */
  lockedAt: string
  /** Individual file hashes for granular drift detection */
  files: Record<string, string>
}

/** The full lockfile structure */
export interface SquadLockfile {
  /** Lockfile schema version */
  lockVersion: 1
  /** Map of squad name -> locked entry */
  squads: Record<string, LockedSquad>
}

/** Result of a drift check for a single squad */
export interface DriftResult {
  /** Squad name */
  name: string
  /** Whether any drift was detected */
  drifted: boolean
  /** Files that changed */
  changedFiles: string[]
  /** Files that were added (not in lock) */
  addedFiles: string[]
  /** Files that were removed (in lock but missing on disk) */
  removedFiles: string[]
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Relative path to the lockfile within project root */
export const LOCKFILE_PATH = '.buildpact/squad-lock.yaml'

// ---------------------------------------------------------------------------
// Pure functions
// ---------------------------------------------------------------------------

/** Compute SHA-256 hash of a string */
export function sha256(content: string): string {
  return createHash('sha256').update(content, 'utf-8').digest('hex')
}

/** Serialize a lockfile to YAML-like format */
export function serializeLockfile(lock: SquadLockfile): string {
  const lines: string[] = [
    '# BuildPact Squad Lockfile — DO NOT EDIT MANUALLY',
    '# Generated by: buildpact squad add / buildpact squad update',
    `lock_version: ${lock.lockVersion}`,
    'squads:',
  ]

  for (const [name, entry] of Object.entries(lock.squads)) {
    lines.push(`  ${name}:`)
    lines.push(`    version: "${entry.version}"`)
    lines.push(`    content_hash: "${entry.contentHash}"`)
    lines.push(`    locked_at: "${entry.lockedAt}"`)
    lines.push(`    files:`)
    for (const [filePath, hash] of Object.entries(entry.files)) {
      lines.push(`      "${filePath}": "${hash}"`)
    }
  }

  return lines.join('\n') + '\n'
}

/** Parse a lockfile from YAML-like text */
export function parseLockfile(content: string): Result<SquadLockfile> {
  const lockfile: SquadLockfile = { lockVersion: 1, squads: {} }

  const lines = content.split('\n')
  let currentSquad: string | undefined
  let inFiles = false

  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line || line.startsWith('#')) continue

    const trimmed = line.trimStart()
    const indent = line.length - trimmed.length

    if (trimmed.startsWith('lock_version:')) {
      const val = trimmed.slice('lock_version:'.length).trim()
      if (val !== '1') {
        return err({
          code: ERROR_CODES.CONFIG_INVALID,
          i18nKey: 'error.squad.lock_version_unsupported',
          params: { version: val },
        })
      }
      continue
    }

    if (trimmed === 'squads:') continue

    // Squad name line (indent 2, ends with colon, no value)
    if (indent === 2 && trimmed.endsWith(':') && !trimmed.includes('"')) {
      currentSquad = trimmed.slice(0, -1)
      lockfile.squads[currentSquad] = {
        name: currentSquad,
        version: '',
        contentHash: '',
        lockedAt: '',
        files: {},
      }
      inFiles = false
      continue
    }

    if (!currentSquad) continue
    const entry = lockfile.squads[currentSquad]!

    if (indent === 4 && trimmed.startsWith('version:')) {
      entry.version = trimmed.slice('version:'.length).trim().replace(/^"|"$/g, '')
      inFiles = false
      continue
    }
    if (indent === 4 && trimmed.startsWith('content_hash:')) {
      entry.contentHash = trimmed.slice('content_hash:'.length).trim().replace(/^"|"$/g, '')
      inFiles = false
      continue
    }
    if (indent === 4 && trimmed.startsWith('locked_at:')) {
      entry.lockedAt = trimmed.slice('locked_at:'.length).trim().replace(/^"|"$/g, '')
      inFiles = false
      continue
    }
    if (indent === 4 && trimmed === 'files:') {
      inFiles = true
      continue
    }

    // File hash entry (indent 6)
    if (indent === 6 && inFiles && currentSquad) {
      const colonIdx = trimmed.indexOf(':')
      if (colonIdx !== -1) {
        const filePath = trimmed.slice(0, colonIdx).trim().replace(/^"|"$/g, '')
        const hash = trimmed.slice(colonIdx + 1).trim().replace(/^"|"$/g, '')
        entry.files[filePath] = hash
      }
    }
  }

  return ok(lockfile)
}

// ---------------------------------------------------------------------------
// I/O functions
// ---------------------------------------------------------------------------

/** Recursively collect all files in a directory, returning relative paths */
async function collectFiles(dir: string, baseDir: string): Promise<string[]> {
  const collected: string[] = []
  let entries: string[]
  try {
    entries = await readdir(dir)
  } catch {
    return collected
  }

  for (const entry of entries) {
    const fullPath = join(dir, entry)
    const st = await stat(fullPath)
    if (st.isDirectory()) {
      const nested = await collectFiles(fullPath, baseDir)
      collected.push(...nested)
    } else {
      collected.push(relative(baseDir, fullPath))
    }
  }

  return collected.sort()
}

/**
 * Build a LockedSquad entry by scanning a squad directory.
 * Reads all files, computes per-file hashes, and an overall content hash.
 */
export async function buildLockedEntry(
  squadDir: string,
  squadName: string,
  nowIso?: string,
): Promise<Result<LockedSquad>> {
  const files = await collectFiles(squadDir, squadDir)
  const fileHashes: Record<string, string> = {}
  const allContent: string[] = []

  // Read squad.yaml for version
  let version = 'unknown'
  try {
    const yamlContent = await readFile(join(squadDir, 'squad.yaml'), 'utf-8')
    for (const line of yamlContent.split('\n')) {
      const trimmed = line.trim()
      if (trimmed.startsWith('version:')) {
        version = trimmed.slice('version:'.length).trim().replace(/^["']|["']$/g, '')
        break
      }
    }
  } catch {
    // squad.yaml missing — proceed with 'unknown'
  }

  for (const filePath of files) {
    try {
      const content = await readFile(join(squadDir, filePath), 'utf-8')
      const hash = sha256(content)
      fileHashes[filePath] = hash
      allContent.push(`${filePath}:${hash}`)
    } catch {
      // Skip unreadable files
    }
  }

  const contentHash = sha256(allContent.join('\n'))

  return ok({
    name: squadName,
    version,
    contentHash,
    lockedAt: nowIso ?? new Date().toISOString(),
    files: fileHashes,
  })
}

/**
 * Read the lockfile from disk. Returns empty lockfile if not found.
 */
export async function readLockfile(projectDir: string): Promise<Result<SquadLockfile>> {
  const lockPath = join(projectDir, LOCKFILE_PATH)
  try {
    const content = await readFile(lockPath, 'utf-8')
    return parseLockfile(content)
  } catch {
    return ok({ lockVersion: 1, squads: {} })
  }
}

/**
 * Write the lockfile to disk.
 */
export async function writeLockfile(projectDir: string, lock: SquadLockfile): Promise<Result<void>> {
  const lockPath = join(projectDir, LOCKFILE_PATH)
  try {
    await writeFile(lockPath, serializeLockfile(lock), 'utf-8')
    return ok(undefined)
  } catch (cause) {
    return err({
      code: ERROR_CODES.FILE_WRITE_FAILED,
      i18nKey: 'error.file.write_failed',
      params: { path: lockPath, reason: String(cause) },
      cause,
    })
  }
}

/**
 * Check a single squad for drift against the lockfile entry.
 */
export async function checkSquadDrift(
  squadDir: string,
  locked: LockedSquad,
): Promise<DriftResult> {
  const currentFiles = await collectFiles(squadDir, squadDir)
  const lockedFilePaths = Object.keys(locked.files)

  const changedFiles: string[] = []
  const addedFiles: string[] = []
  const removedFiles: string[] = []

  // Check for changed and added files
  for (const filePath of currentFiles) {
    const lockedHash = locked.files[filePath]
    if (lockedHash === undefined) {
      addedFiles.push(filePath)
      continue
    }
    try {
      const content = await readFile(join(squadDir, filePath), 'utf-8')
      const currentHash = sha256(content)
      if (currentHash !== lockedHash) {
        changedFiles.push(filePath)
      }
    } catch {
      // Can't read — treat as removed
      removedFiles.push(filePath)
    }
  }

  // Check for removed files
  for (const filePath of lockedFilePaths) {
    if (!currentFiles.includes(filePath)) {
      removedFiles.push(filePath)
    }
  }

  return {
    name: locked.name,
    drifted: changedFiles.length > 0 || addedFiles.length > 0 || removedFiles.length > 0,
    changedFiles,
    addedFiles,
    removedFiles,
  }
}

/**
 * Check all squads for drift. Returns drift results per squad.
 */
export async function checkAllSquadDrift(projectDir: string): Promise<Result<DriftResult[]>> {
  const lockResult = await readLockfile(projectDir)
  if (!lockResult.ok) return lockResult as Result<DriftResult[]>

  const lock = lockResult.value
  const results: DriftResult[] = []

  for (const [name, locked] of Object.entries(lock.squads)) {
    const squadDir = join(projectDir, '.buildpact', 'squads', name)
    const drift = await checkSquadDrift(squadDir, locked)
    results.push(drift)
  }

  return ok(results)
}

/**
 * Lock a single squad (add or update its entry in the lockfile).
 */
export async function lockSquad(projectDir: string, squadName: string): Promise<Result<void>> {
  const squadDir = join(projectDir, '.buildpact', 'squads', squadName)
  const lockResult = await readLockfile(projectDir)
  if (!lockResult.ok) return lockResult as Result<void>

  const lock = lockResult.value
  const entryResult = await buildLockedEntry(squadDir, squadName)
  if (!entryResult.ok) return entryResult as Result<void>

  lock.squads[squadName] = entryResult.value
  return writeLockfile(projectDir, lock)
}

/**
 * Update all squad locks (re-scan and re-hash all installed squads).
 */
export async function updateAllLocks(projectDir: string): Promise<Result<string[]>> {
  const squadsDir = join(projectDir, '.buildpact', 'squads')
  let entries: string[]
  try {
    entries = await readdir(squadsDir)
  } catch {
    return ok([])
  }

  const lock: SquadLockfile = { lockVersion: 1, squads: {} }
  const updated: string[] = []

  for (const entry of entries) {
    const squadDir = join(squadsDir, entry)
    const st = await stat(squadDir)
    if (!st.isDirectory()) continue

    const entryResult = await buildLockedEntry(squadDir, entry)
    if (entryResult.ok) {
      lock.squads[entry] = entryResult.value
      updated.push(entry)
    }
  }

  const writeResult = await writeLockfile(projectDir, lock)
  if (!writeResult.ok) return writeResult as Result<string[]>

  return ok(updated)
}
