/**
 * Migrate-to-agent command handler.
 * Validates existing BuildPact artifacts and generates Agent Mode configuration.
 * @see FR-1051 — Prompt-to-Agent Mode Migration Path
 * @see US-047 — Epic 10.5: Prompt-to-Agent Mode Migration Path (v2.0)
 */

import * as clack from '@clack/prompts'
import { readFile, mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { ok, err, ERROR_CODES } from '../../contracts/errors.js'
import type { Result } from '../../contracts/errors.js'
import type { CommandHandler } from '../registry.js'
import type { SupportedLanguage } from '../../contracts/i18n.js'
import { createI18n } from '../../foundation/i18n.js'
import { AuditLogger } from '../../foundation/audit.js'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Status of a file checked during migration validation */
export type FileStatus = 'present' | 'missing'

/** An item in the compatibility report */
export interface CompatibilityIssue {
  /** Relative path of the file (relative to projectDir) */
  file: string
  /** Whether the file is present or missing */
  status: FileStatus
  /** Remediation step if status is 'missing' */
  remediation?: string
}

/** Result of validating .buildpact/ structure */
export interface ValidationResult {
  issues: CompatibilityIssue[]
  /** true when all required files are present */
  allPresent: boolean
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

/** Required files for Agent Mode migration */
const REQUIRED_FILES: Array<{ rel: string; remediation_en: string; remediation_pt: string }> = [
  {
    rel: '.buildpact/config.yaml',
    remediation_en: 'Run `npx buildpact init` to initialise project configuration.',
    remediation_pt: 'Execute `npx buildpact init` para inicializar a configuração do projeto.',
  },
  {
    rel: '.buildpact/constitution.md',
    remediation_en:
      'Run `npx buildpact init` or create .buildpact/constitution.md manually with your project rules.',
    remediation_pt:
      'Execute `npx buildpact init` ou crie .buildpact/constitution.md manualmente com as regras do projeto.',
  },
  {
    rel: '.buildpact/project-context.md',
    remediation_en:
      'Create .buildpact/project-context.md with domain description, architecture overview, and key conventions.',
    remediation_pt:
      'Crie .buildpact/project-context.md com descrição do domínio, visão geral da arquitetura e convenções principais.',
  },
]

/**
 * Validate existing .buildpact/ files required for Agent Mode.
 * Returns an array of CompatibilityIssues with file-level status and remediation.
 */
export async function validateBuildpactFiles(
  projectDir: string,
  lang: SupportedLanguage = 'en',
): Promise<ValidationResult> {
  const issues: CompatibilityIssue[] = []

  for (const entry of REQUIRED_FILES) {
    const absPath = join(projectDir, entry.rel)
    let present = false
    try {
      await readFile(absPath, 'utf-8')
      present = true
    } catch {
      present = false
    }

    if (present) {
      issues.push({ file: entry.rel, status: 'present' })
    } else {
      issues.push({
        file: entry.rel,
        status: 'missing',
        remediation: lang === 'pt-br' ? entry.remediation_pt : entry.remediation_en,
      })
    }
  }

  const allPresent = issues.every((i) => i.status === 'present')
  return { issues, allPresent }
}

// ---------------------------------------------------------------------------
// Agent Mode config builder
// ---------------------------------------------------------------------------

/**
 * Build the content of .buildpact/agent-mode.yaml.
 * The mode is set to 'prompt' by default — user must change to 'agent' to activate.
 */
export function buildAgentModeConfig(squadName: string | undefined, nowMs: number = Date.now()): string {
  const generatedAt = new Date(nowMs).toISOString()
  const squadLine = squadName ? `  squad: ${squadName}` : '  squad: ~  # set to your squad name'

  return [
    '# BuildPact Agent Mode Configuration',
    `# Generated by: buildpact migrate-to-agent`,
    `# Generated at: ${generatedAt}`,
    '#',
    '# To activate Agent Mode: change mode from "prompt" to "agent"',
    '# The project continues working in Prompt Mode until you make that change.',
    '',
    '# Current operating mode',
    '# Options: prompt | agent',
    'mode: prompt',
    '',
    '# Agent Mode capabilities (enabled when mode is set to agent)',
    'agent_capabilities:',
    '  autonomous_execution: true',
    '  multi_agent_coordination: true',
    '  parallel_wave_execution: true',
    '',
    '# Active squad for agent coordination',
    'squad_config:',
    squadLine,
    '',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// Compatibility report builder
// ---------------------------------------------------------------------------

/**
 * Build the markdown compatibility report content.
 * Lists validation results with file references and remediation steps.
 */
export function buildCompatibilityReport(
  issues: CompatibilityIssue[],
  lang: SupportedLanguage,
  nowMs: number = Date.now(),
): string {
  const generatedAt = new Date(nowMs).toISOString()
  const isEn = lang !== 'pt-br'

  const title = isEn
    ? '# BuildPact Agent Mode Compatibility Report'
    : '# Relatório de Compatibilidade — Modo Agente BuildPact'

  const subtitle = isEn
    ? `Generated: ${generatedAt}`
    : `Gerado em: ${generatedAt}`

  const overviewTitle = isEn ? '## Overview' : '## Visão Geral'
  const presentCount = issues.filter((i) => i.status === 'present').length
  const missingCount = issues.filter((i) => i.status === 'missing').length

  const overviewBody = isEn
    ? `- Files checked: ${issues.length}\n- Present: ${presentCount}\n- Missing: ${missingCount}`
    : `- Arquivos verificados: ${issues.length}\n- Presentes: ${presentCount}\n- Ausentes: ${missingCount}`

  const filesTitle = isEn ? '## File Validation' : '## Validação de Arquivos'
  const fileLines: string[] = []
  for (const issue of issues) {
    const icon = issue.status === 'present' ? '✅' : '❌'
    const statusLabel = issue.status === 'present'
      ? (isEn ? 'present' : 'presente')
      : (isEn ? 'missing' : 'ausente')
    fileLines.push(`- ${icon} \`${issue.file}\` — ${statusLabel}`)
    if (issue.remediation) {
      fileLines.push(`  - **${isEn ? 'Fix' : 'Correção'}:** ${issue.remediation}`)
    }
  }

  const nextTitle = isEn ? '## Next Steps' : '## Próximos Passos'
  const nextBody = isEn
    ? [
        '1. Fix any missing files listed above.',
        '2. Review `.buildpact/agent-mode.yaml` and confirm capabilities.',
        '3. When ready, change `mode: prompt` → `mode: agent` in `.buildpact/agent-mode.yaml`.',
        '4. Run `npx buildpact doctor` to verify the full setup.',
        '',
        '> **Note:** Your project continues working in Prompt Mode until Agent Mode is explicitly activated.',
      ].join('\n')
    : [
        '1. Corrija os arquivos ausentes listados acima.',
        '2. Revise `.buildpact/agent-mode.yaml` e confirme as capacidades.',
        '3. Quando pronto, altere `mode: prompt` → `mode: agent` em `.buildpact/agent-mode.yaml`.',
        '4. Execute `npx buildpact doctor` para verificar a configuração completa.',
        '',
        '> **Nota:** Seu projeto continua funcionando no Modo Prompt até que o Modo Agente seja explicitamente ativado.',
      ].join('\n')

  return [title, subtitle, '', overviewTitle, overviewBody, '', filesTitle, ...fileLines, '', nextTitle, nextBody, ''].join('\n')
}

// ---------------------------------------------------------------------------
// Language helper
// ---------------------------------------------------------------------------

/** Read language from .buildpact/config.yaml, fallback to 'en' */
async function readLanguage(projectDir: string): Promise<SupportedLanguage> {
  try {
    const content = await readFile(join(projectDir, '.buildpact', 'config.yaml'), 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (trimmed.startsWith('language:')) {
        const value = trimmed.slice('language:'.length).trim().replace(/^["']|["']$/g, '')
        if (value === 'pt-br' || value === 'en') return value
      }
    }
  } catch {
    // Config missing — fall back to English
  }
  return 'en'
}

/** Read active_squad from .buildpact/config.yaml, returns undefined if not set */
async function readActiveSquadName(projectDir: string): Promise<string | undefined> {
  try {
    const content = await readFile(join(projectDir, '.buildpact', 'config.yaml'), 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (trimmed.startsWith('active_squad:')) {
        const value = trimmed.slice('active_squad:'.length).trim().replace(/^["']|["']$/g, '')
        if (value && value !== 'none') return value
      }
    }
  } catch {
    // Config missing
  }
  return undefined
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

export const handler: CommandHandler = {
  async run(_args: string[]): Promise<Result<void>> {
    const projectDir = process.cwd()
    const lang = await readLanguage(projectDir)
    const i18n = createI18n(lang)
    const audit = new AuditLogger(join(projectDir, '.buildpact', 'audit', 'audit.log'))

    clack.intro(i18n.t('cli.migrate_to_agent.welcome'))

    // Log intent
    await audit.log({
      action: 'migrate_to_agent.start',
      agent: 'migrate-to-agent',
      files: [],
      outcome: 'success',
    })

    const spinner = clack.spinner()
    spinner.start(i18n.t('cli.migrate_to_agent.validating'))

    // Step 1: Validate existing files
    const { issues, allPresent } = await validateBuildpactFiles(projectDir, lang)

    spinner.stop(i18n.t('cli.migrate_to_agent.validated'))

    // Report each file status
    for (const issue of issues) {
      if (issue.status === 'present') {
        clack.log.success(`${issue.file}`)
      } else {
        clack.log.warn(`${issue.file} — ${i18n.t('cli.migrate_to_agent.missing')}`)
        if (issue.remediation) {
          clack.log.info(issue.remediation)
        }
      }
    }

    if (!allPresent) {
      clack.log.warn(i18n.t('cli.migrate_to_agent.warn_missing_files'))
    }

    // Step 2: Read squad name for config generation
    const squadName = await readActiveSquadName(projectDir)

    // Step 3: Generate agent-mode.yaml
    const agentModeConfigPath = join(projectDir, '.buildpact', 'agent-mode.yaml')
    const agentModeContent = buildAgentModeConfig(squadName)

    try {
      await mkdir(join(projectDir, '.buildpact'), { recursive: true })
      await writeFile(agentModeConfigPath, agentModeContent, 'utf-8')
    } catch (cause) {
      const result = err<void>({
        code: ERROR_CODES.FILE_WRITE_FAILED,
        i18nKey: 'error.file.write_failed',
        params: { path: agentModeConfigPath, reason: String(cause) },
        cause,
      })
      await audit.log({
        action: 'migrate_to_agent.write_config',
        agent: 'migrate-to-agent',
        files: [],
        outcome: 'failure',
        error: String(cause),
      })
      return result
    }

    clack.log.success(i18n.t('cli.migrate_to_agent.config_written', { path: agentModeConfigPath }))

    // Step 4: Write compatibility report
    const reportPath = join(projectDir, '.buildpact', 'agent-mode-compatibility.md')
    const reportContent = buildCompatibilityReport(issues, lang)

    try {
      await writeFile(reportPath, reportContent, 'utf-8')
    } catch (cause) {
      const result = err<void>({
        code: ERROR_CODES.FILE_WRITE_FAILED,
        i18nKey: 'error.file.write_failed',
        params: { path: reportPath, reason: String(cause) },
        cause,
      })
      await audit.log({
        action: 'migrate_to_agent.write_report',
        agent: 'migrate-to-agent',
        files: [],
        outcome: 'failure',
        error: String(cause),
      })
      return result
    }

    clack.log.success(i18n.t('cli.migrate_to_agent.report_written', { path: reportPath }))

    await audit.log({
      action: 'migrate_to_agent.complete',
      agent: 'migrate-to-agent',
      files: [agentModeConfigPath, reportPath],
      outcome: 'success',
    })

    clack.outro(i18n.t('cli.migrate_to_agent.outro'))

    return ok(undefined)
  },
}
