// CliError — canonical error type for all business logic
// Contracts are stubs in Alpha — shapes stable from commit one

/**
 * Canonical error type — used as E in Result<T, E>.
 * Business logic NEVER throws; it returns Result<T, CliError>.
 * Only programming errors (invariant violations) use throw.
 */
export interface CliError {
  /** SCREAMING_SNAKE_CASE error code: 'SQUAD_NOT_FOUND' */
  code: string
  /** dot-notation i18n key: 'error.squad.not_found' */
  i18nKey: string
  /** Interpolation params for the i18n message */
  params?: Record<string, string>
  /** Release phase when this will be implemented: 'v1.0' for stubs */
  phase?: string
  /** Original underlying error if wrapping */
  cause?: unknown
}

/**
 * Result type — all fallible business functions return this.
 * Never throw for business logic errors.
 */
export type Result<T, E = CliError> =
  | { ok: true; value: T }
  | { ok: false; error: E }

/** Convenience constructor for success */
export function ok<T>(value: T): Result<T> {
  return { ok: true, value }
}

/** Convenience constructor for failure */
export function err<T = never>(error: CliError): Result<T> {
  return { ok: false, error }
}

/** Predefined error codes */
export const ERROR_CODES = {
  SQUAD_NOT_FOUND: 'SQUAD_NOT_FOUND',
  SQUAD_VALIDATION_FAILED: 'SQUAD_VALIDATION_FAILED',
  IDE_CONFIG_FAILED: 'IDE_CONFIG_FAILED',
  REMOTE_FETCH_FAILED: 'REMOTE_FETCH_FAILED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  FILE_WRITE_FAILED: 'FILE_WRITE_FAILED',
  FILE_READ_FAILED: 'FILE_READ_FAILED',
  ORCHESTRATOR_TOO_LONG: 'ORCHESTRATOR_TOO_LONG',
  MISSING_ORCHESTRATOR_HEADER: 'MISSING_ORCHESTRATOR_HEADER',
  MISSING_IMPLEMENTATION_NOTES: 'MISSING_IMPLEMENTATION_NOTES',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  CONSTITUTION_NOT_FOUND: 'CONSTITUTION_NOT_FOUND',
  CONSTITUTION_EMPTY: 'CONSTITUTION_EMPTY',
  CONSTITUTION_VIOLATION: 'CONSTITUTION_VIOLATION',
  FAILOVER_EXHAUSTED: 'FAILOVER_EXHAUSTED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  SPEC_NOT_FOUND: 'SPEC_NOT_FOUND',
  SQUAD_INVALID_NAME: 'SQUAD_INVALID_NAME',
  AGENT_LEVEL_STORE_FAILED: 'AGENT_LEVEL_STORE_FAILED',
  AGENT_LOAD_FAILED: 'AGENT_LOAD_FAILED',
  TARGET_TOO_LARGE: 'TARGET_TOO_LARGE',
  EXPERT_ONLY: 'EXPERT_ONLY',
  RATCHET_BRANCH_FAILED: 'RATCHET_BRANCH_FAILED',
  RATCHET_COMMIT_FAILED: 'RATCHET_COMMIT_FAILED',
  RATCHET_REVERT_FAILED: 'RATCHET_REVERT_FAILED',
  TASK_RESULT_INVALID: 'TASK_RESULT_INVALID',
  MISSING_ARG: 'MISSING_ARG',
  CONSTITUTION_MODIFICATION_BLOCKED: 'CONSTITUTION_MODIFICATION_BLOCKED',
  GIT_COMMAND_FAILED: 'GIT_COMMAND_FAILED',
  SCHEMA_INCOMPATIBLE: 'SCHEMA_INCOMPATIBLE',
  CLI_TOO_OLD: 'CLI_TOO_OLD',
  MIGRATION_FAILED: 'MIGRATION_FAILED',
  ADOPT_FAILED: 'ADOPT_FAILED',
  ADOPT_SCAN_FAILED: 'ADOPT_SCAN_FAILED',
  HUB_NO_RESULTS: 'HUB_NO_RESULTS',
  HUB_SQUAD_NOT_FOUND: 'HUB_SQUAD_NOT_FOUND',
  READONLY_MODE: 'READONLY_MODE',
  AGENT_ALREADY_RUNNING: 'AGENT_ALREADY_RUNNING',
  AGENT_NOT_RUNNING: 'AGENT_NOT_RUNNING',
  AGENT_STALE_PID: 'AGENT_STALE_PID',
  AGENT_PAUSED: 'AGENT_PAUSED',
  RBAC_CONFIG_INVALID: 'RBAC_CONFIG_INVALID',
  RBAC_DENIED: 'RBAC_DENIED',
  REVIEW_INVALID: 'REVIEW_INVALID',
  REVIEW_SUBMIT_FAILED: 'REVIEW_SUBMIT_FAILED',
  REVIEW_FETCH_FAILED: 'REVIEW_FETCH_FAILED',
  CERTIFICATION_FAILED: 'CERTIFICATION_FAILED',

  // ── Fase 0: Multi-Agent Orchestration (Role Boundary, Handoff, Ledger) ──
  ROLE_BOUNDARY_VIOLATION: 'ROLE_BOUNDARY_VIOLATION',
  ROLE_BLOCKED_TOOL_CALL: 'ROLE_BLOCKED_TOOL_CALL',
  ROLE_BLOCKED_FILE_OPERATION: 'ROLE_BLOCKED_FILE_OPERATION',
  HANDOFF_PACKET_INVALID: 'HANDOFF_PACKET_INVALID',
  HANDOFF_MISSING_ACCEPTANCE_CRITERIA: 'HANDOFF_MISSING_ACCEPTANCE_CRITERIA',
  HANDOFF_NO_TARGET_AGENT: 'HANDOFF_NO_TARGET_AGENT',
  ARTIFACT_CHANGE_NO_REASON: 'ARTIFACT_CHANGE_NO_REASON',
  ARTIFACT_CHANGE_NO_CAUSAL_TASK: 'ARTIFACT_CHANGE_NO_CAUSAL_TASK',
  LEDGER_ENTRY_MISSING_DETAILS: 'LEDGER_ENTRY_MISSING_DETAILS',
  LEDGER_ORPHAN_REFERENCE: 'LEDGER_ORPHAN_REFERENCE',
  ORCHESTRATOR_CONTEXT_POLLUTION: 'ORCHESTRATOR_CONTEXT_POLLUTION',
  ORCHESTRATOR_STATE_READ_FAILED: 'ORCHESTRATOR_STATE_READ_FAILED',

  // ── Fase 1: Foundations ──────────────────────────────────────────────────

  // Verification Gate (3.1)
  VERIFICATION_EVIDENCE_MISSING: 'VERIFICATION_EVIDENCE_MISSING',
  VERIFICATION_EVIDENCE_STALE: 'VERIFICATION_EVIDENCE_STALE',
  VERIFICATION_CLAIM_UNSUBSTANTIATED: 'VERIFICATION_CLAIM_UNSUBSTANTIATED',

  // Debug Protocol (3.2)
  DEBUG_PHASE_SKIPPED: 'DEBUG_PHASE_SKIPPED',
  DEBUG_ROOT_CAUSE_MISSING: 'DEBUG_ROOT_CAUSE_MISSING',
  DEBUG_FIX_LIMIT_REACHED: 'DEBUG_FIX_LIMIT_REACHED',

  // Clarify Engine (6.1)
  CLARIFICATION_MARKERS_UNRESOLVED: 'CLARIFICATION_MARKERS_UNRESOLVED',
  CLARIFICATION_MARKER_NO_CATEGORY: 'CLARIFICATION_MARKER_NO_CATEGORY',

  // Requirement Quality (6.3)
  REQUIREMENT_QUALITY_BELOW_THRESHOLD: 'REQUIREMENT_QUALITY_BELOW_THRESHOLD',

  // Build Checkpoint (8.3)
  BUILD_ABANDONED: 'BUILD_ABANDONED',
  BUILD_CHECKPOINT_CORRUPT: 'BUILD_CHECKPOINT_CORRUPT',

  // Distillator (10.1)
  DISTILLATE_ROUND_TRIP_FAILED: 'DISTILLATE_ROUND_TRIP_FAILED',
  DISTILLATE_ZERO_CONTENT: 'DISTILLATE_ZERO_CONTENT',

  // Dispatch Table (12.1)
  DISPATCH_NO_MATCHING_RULE: 'DISPATCH_NO_MATCHING_RULE',

  // Metrics Ledger (12.3)
  METRICS_WRITE_FAILED: 'METRICS_WRITE_FAILED',

  // Budget Policies (14.2)
  BUDGET_POLICY_HARD_STOP: 'BUDGET_POLICY_HARD_STOP',
  BUDGET_POLICY_NOT_FOUND: 'BUDGET_POLICY_NOT_FOUND',

  // ── Fase 2: Enforcement ─────────────────────────────────────────────────

  // TDD Enforcer (3.3)
  TDD_PHASE_VIOLATION: 'TDD_PHASE_VIOLATION',
  TDD_TEST_NOT_FAILING: 'TDD_TEST_NOT_FAILING',
  TDD_PRODUCTION_BEFORE_TEST: 'TDD_PRODUCTION_BEFORE_TEST',

  // Spec-First Gate (3.7)
  SPEC_NOT_APPROVED: 'SPEC_NOT_APPROVED',
  SPEC_APPROVAL_BYPASSED: 'SPEC_APPROVAL_BYPASSED',

  // Experiment Loop (4.1)
  EXPERIMENT_BASELINE_MISSING: 'EXPERIMENT_BASELINE_MISSING',
  EXPERIMENT_NO_PRIMARY_METRIC: 'EXPERIMENT_NO_PRIMARY_METRIC',
  EXPERIMENT_BUDGET_EXCEEDED: 'EXPERIMENT_BUDGET_EXCEEDED',

  // Research Phase (6.4)
  RESEARCH_BLOCKING_UNRESOLVED: 'RESEARCH_BLOCKING_UNRESOLVED',

  // Self-Critique (8.1)
  SELF_CRITIQUE_MISSING: 'SELF_CRITIQUE_MISSING',
  SELF_CRITIQUE_INSUFFICIENT: 'SELF_CRITIQUE_INSUFFICIENT',

  // Adversarial Review (10.2)
  ADVERSARIAL_ZERO_FINDINGS: 'ADVERSARIAL_ZERO_FINDINGS',

  // Session Forensics (12.2)
  FORENSICS_NO_AUDIT_DATA: 'FORENSICS_NO_AUDIT_DATA',

  // Dispatch Guard (12.5)
  DISPATCH_PREREQUISITES_INCOMPLETE: 'DISPATCH_PREREQUISITES_INCOMPLETE',

  // Approval Gates (14.3)
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_TIMEOUT: 'APPROVAL_TIMEOUT',

  // ── Fase 3: Integration ─────────────────────────────────────────────────

  // Two-Stage Review (3.4)
  REVIEW_SPEC_COMPLIANCE_FAILED: 'REVIEW_SPEC_COMPLIANCE_FAILED',
  REVIEW_CODE_QUALITY_FAILED: 'REVIEW_CODE_QUALITY_FAILED',
  REVIEW_STAGE_ORDER_VIOLATION: 'REVIEW_STAGE_ORDER_VIOLATION',

  // Consistency Analyzer (6.2)
  CONSISTENCY_VIOLATION_CRITICAL: 'CONSISTENCY_VIOLATION_CRITICAL',
  CONSISTENCY_COVERAGE_GAP: 'CONSISTENCY_COVERAGE_GAP',

  // Quality Gates (8.2)
  QUALITY_GATE_LAYER1_FAILED: 'QUALITY_GATE_LAYER1_FAILED',
  QUALITY_GATE_LAYER2_FAILED: 'QUALITY_GATE_LAYER2_FAILED',

  // Readiness Formal (10.4)
  READINESS_NOT_READY: 'READINESS_NOT_READY',

  // Reassessment (12.4)
  REASSESSMENT_PLAN_INVALIDATED: 'REASSESSMENT_PLAN_INVALIDATED',

  // Faithfulness Checker (20.1)
  FAITHFULNESS_BELOW_THRESHOLD: 'FAITHFULNESS_BELOW_THRESHOLD',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
