// Task Dispatch Payload — FR-302
// Contracts are stubs in Alpha — shapes stable from commit one

// ---------------------------------------------------------------------------
// Goal Ancestry — traces task objective back to project mission (Paperclip 14.1)
// ---------------------------------------------------------------------------

/** Full goal chain from mission to task — agents always know the "why" */
export interface GoalAncestry {
  /** Top-level project mission (e.g. "Build the #1 AI note-taking app") */
  mission: string
  /** Current project goal (e.g. "Ship MVP with core CRUD + search") */
  projectGoal: string
  /** Phase/wave goal (e.g. "Implement data model and API") */
  phaseGoal: string
  /** Specific task objective (e.g. "Create user entity with validation") */
  taskObjective: string
}

/** Payload dispatched to isolated subagents via Task() */
export interface TaskDispatchPayload {
  /** Unique task identifier within the session */
  taskId: string
  /** Type of task being dispatched */
  type: 'specify' | 'plan' | 'execute' | 'verify' | 'quick' | 'optimize'
  /** The specific plan or spec content for this task */
  content: string
  /** Task-specific context (codebase snippets, prior outputs) */
  context?: string
  /** Target output path for generated artifacts */
  outputPath?: string
  /** Budget constraint for this task in USD */
  budgetUsd?: number
  /** Path to the project constitution file, if it exists (FR-202) */
  constitutionPath?: string
  /** Goal ancestry — why this task matters in the bigger picture */
  goalAncestry?: GoalAncestry | undefined
}

/** Result returned by a completed subagent task */
export interface TaskResult {
  taskId: string
  success: boolean
  /** Artifacts generated by the task (file paths) */
  artifacts: string[]
  /** Token usage for cost tracking */
  tokensUsed?: number
  /** Estimated cost in USD */
  costUsd?: number
  /** Error details if task failed */
  error?: string
  /** Response content from the subagent */
  response?: string
}

// ---------------------------------------------------------------------------
// Role Boundary — whitelist/blacklist per agent role (Original 16.1)
// ---------------------------------------------------------------------------

/** Pattern type for matching agent actions */
export type ActionPatternType = 'tool_call' | 'output_pattern' | 'file_operation'

/** A single action pattern for whitelist/blacklist matching */
export interface ActionPattern {
  /** What kind of action this pattern matches */
  type: ActionPatternType
  /** Regex pattern to match against (tool name, output content, or file path) */
  pattern: string
  /** Human-readable description of what this pattern covers */
  description: string
}

/** Role boundary definition — what an agent CAN and CANNOT do */
export interface RoleBoundary {
  /** Role identifier (e.g. "orchestrator", "developer", "reviewer") */
  agentRole: string
  /** Actions this role is allowed to perform */
  allowedActions: ActionPattern[]
  /** Actions this role is blocked from performing */
  blockedActions: ActionPattern[]
}

/** Recorded when a role boundary check fails */
export interface RoleBoundaryViolation {
  /** The agent role that attempted the action */
  agentRole: string
  /** The action that was attempted */
  attemptedAction: string
  /** The pattern that matched the blocked action */
  matchedPattern: ActionPattern
  /** ISO timestamp of the violation */
  timestamp: string
}

// ---------------------------------------------------------------------------
// Handoff Protocol — formal transition between agents (Original 16.2)
// ---------------------------------------------------------------------------

/** Formal handoff packet for agent-to-agent transitions */
export interface HandoffPacket {
  /** Unique handoff identifier (HOF-001) */
  id: string
  /** Agent sending the handoff */
  fromAgent: string
  /** Agent receiving the handoff */
  toAgent: string
  /** Task being handed off */
  taskId: string
  /** Condensed context briefing for the receiver */
  briefing: string
  /** Goal ancestry — why this task matters */
  goalAncestry?: GoalAncestry | undefined
  /** What the receiver is expected to produce */
  expectedOutput: {
    /** Type of output ("code", "spec", "review", "plan") */
    type: string
    /** Files that should be produced */
    artifacts: string[]
    /** How to know the work is done */
    acceptanceCriteria: string[]
  }
  /** File paths the receiver needs to read */
  contextFiles: string[]
  /** Relevant decisions from the decisions log */
  priorDecisions: string[]
  /** Constraints (budget, time, scope) */
  constraints: string[]
  /** ISO timestamp */
  timestamp: string
}

/** Result of validating a handoff packet */
export interface HandoffValidation {
  /** Whether the packet is valid for dispatch */
  valid: boolean
  /** Fields that are missing or invalid */
  missingFields: string[]
  /** Non-blocking warnings */
  warnings: string[]
}

// ---------------------------------------------------------------------------
// Artifact Changelog — track changes to official project documents (Original 16.5)
// ---------------------------------------------------------------------------

/** Types of official project artifacts that are change-tracked */
export type ArtifactType =
  | 'prd' | 'spec' | 'plan' | 'architecture' | 'constitution' | 'epics' | 'stories'
  | 'research' | 'decision' | 'approval' | 'quality-review' | 'budget-policy' | 'checkpoint'

/** A recorded change to an official project artifact */
export interface ArtifactChangeEntry {
  /** Unique change identifier (ACH-001) */
  id: string
  /** Path to the changed artifact */
  artifactPath: string
  /** Type of artifact */
  artifactType: ArtifactType
  /** ISO timestamp */
  timestamp: string
  /** Kind of change */
  changeType: 'added' | 'removed' | 'modified'
  /** Short description of what changed */
  summary: string
  /** Why the change was made */
  reason: string
  /** Task or decision that caused this change */
  causedBy: string
  /** Compact diff (before → after) */
  diff: string
  /** Other artifacts impacted by this change */
  impact: string[]
}

// ---------------------------------------------------------------------------
// Project Ledger — unified temporal index of all events (Original 16.6)
// ---------------------------------------------------------------------------

/** Categories of events tracked in the unified project ledger */
export type LedgerCategory =
  | 'DECISION'
  | 'ARTIFACT_CHANGE'
  | 'HANDOFF'
  | 'APPROVAL'
  | 'BUDGET'
  | 'QUALITY'
  | 'TASK_COMPLETE'
  | 'TASK_FAILED'
  | 'LESSON'
  | 'GOTCHA'
  | 'FORENSIC'
  | 'READINESS'
  | 'REASSESSMENT'
  | 'CONSTITUTION'
  | 'CHECKPOINT'
  | 'VERIFICATION'

/** A single entry in the unified project ledger */
export interface LedgerEntry {
  /** ISO timestamp */
  timestamp: string
  /** Event category */
  category: LedgerCategory
  /** Unique reference ID (e.g. DEC-005, ACH-012, HOF-003) */
  id: string
  /** One-line descriptive summary */
  summary: string
  /** Path to file with full details */
  detailsPath: string
}

// ---------------------------------------------------------------------------
// Verification Gate — evidence-based completion claims (Concept 3.1)
// ---------------------------------------------------------------------------

/** Types of completion claims that require verification evidence */
export type VerificationClaim = 'TESTS_PASS' | 'BUILD_SUCCEEDS' | 'BUG_FIXED' | 'LINT_CLEAN' | 'SPEC_SATISFIED'

/** Proof that a claim was verified by actually running a command */
export interface VerificationEvidence {
  /** Command that was executed (e.g. "npm test") */
  command: string
  /** Exit code of the command */
  exitCode: number
  /** Output from the command (truncated to 2000 chars max) */
  output: string
  /** ISO timestamp of when the command was run */
  timestamp: string
  /** What claim this evidence supports */
  claimType: VerificationClaim
  /** True if evidence is older than the staleness threshold */
  stale: boolean
}

// ---------------------------------------------------------------------------
// Debug Protocol — systematic 4-phase debugging (Concept 3.2)
// ---------------------------------------------------------------------------

/** Mandatory phases for systematic debugging */
export type DebugPhase = 'INVESTIGATION' | 'PATTERN_ANALYSIS' | 'HYPOTHESIS_TEST' | 'IMPLEMENTATION'

/** A single hypothesis in a debug session */
export interface Hypothesis {
  /** What might be causing the bug */
  description: string
  /** Evidence supporting this hypothesis */
  evidenceFor: string[]
  /** Evidence against this hypothesis */
  evidenceAgainst: string[]
  /** Whether this hypothesis has been tested */
  tested: boolean
  /** Result of testing */
  result: 'confirmed' | 'rejected' | 'pending'
}

/** State of a systematic debug session */
export interface DebugSession {
  /** Unique session identifier */
  sessionId: string
  /** Current phase — MUST progress sequentially */
  phase: DebugPhase
  /** Hypotheses generated during investigation */
  hypotheses: Hypothesis[]
  /** Collected evidence (error messages, logs, reproduction steps) */
  evidence: string[]
  /** Number of fix attempts (>= 3 triggers architecture review) */
  fixAttempts: number
  /** True only when root cause is identified — required to enter IMPLEMENTATION */
  rootCauseIdentified: boolean
  /** ISO timestamp of session creation */
  createdAt: string
}

// ---------------------------------------------------------------------------
// Build State — granular checkpoint recovery (Concept 8.3)
// ---------------------------------------------------------------------------

/** Build lifecycle status */
export type BuildStatus = 'PENDING' | 'IN_PROGRESS' | 'PAUSED' | 'ABANDONED' | 'COMPLETED' | 'FAILED'

/** A single checkpoint after a completed task */
export interface BuildCheckpoint {
  /** Task that was completed */
  taskId: string
  /** ISO timestamp of completion */
  completedAt: string
  /** Artifacts produced by the task */
  artifacts: string[]
  /** Cost of this task in USD */
  costUsd: number
}

/** Full build state with checkpoints for resume capability */
export interface BuildState {
  /** Session identifier */
  sessionId: string
  /** Current build status */
  status: BuildStatus
  /** ISO timestamp of build start */
  startedAt: string
  /** ISO timestamp of last checkpoint */
  lastCheckpoint: string
  /** Current wave number */
  currentWave: number
  /** Current task identifier */
  currentTask: string
  /** List of completed task IDs */
  completedTasks: string[]
  /** Checkpoint history */
  checkpoints: BuildCheckpoint[]
  /** Aggregate metrics */
  metrics: {
    totalTasks: number
    completedTasks: number
    totalCostUsd: number
    elapsedSeconds: number
  }
}

// ---------------------------------------------------------------------------
// Dispatch Table — rules-based pipeline routing (Concept 12.1)
// ---------------------------------------------------------------------------

/** What the dispatch table decides to do */
export type DispatchActionType = 'dispatch' | 'stop' | 'skip'

/** Result of evaluating dispatch rules */
export interface DispatchAction {
  /** What to do */
  action: DispatchActionType
  /** Unit type to dispatch (if action='dispatch') */
  unitType?: string | undefined
  /** Unit identifier (if action='dispatch') */
  unitId?: string | undefined
  /** Reason (if action='stop') */
  reason?: string | undefined
  /** Severity level (if action='stop') */
  level?: 'info' | 'warning' | 'error' | undefined
}

/** Pipeline state snapshot used by dispatch rules for decision-making */
export interface DispatchContext {
  /** Project root directory */
  projectDir: string
  /** Current pipeline phase */
  currentPhase: string
  /** Current wave number */
  waveNumber: number
  /** Current task index within wave */
  taskIndex: number
  /** Total tasks in current wave */
  totalTasks: number
  /** Total waves in plan */
  totalWaves: number
  /** Whether the last task succeeded */
  lastTaskSucceeded: boolean
  /** Count of consecutive task failures */
  consecutiveFailures: number
  /** Remaining budget in USD */
  budgetRemaining: number
}

// ---------------------------------------------------------------------------
// Metrics Ledger — per-unit cost/token tracking (Concept 12.3)
// ---------------------------------------------------------------------------

/** Pipeline phase for metrics categorization */
export type MetricsPhase = 'research' | 'planning' | 'execution' | 'verification'

/** Cost and token metrics for a single unit of work */
export interface UnitMetrics {
  /** Type of unit ("research", "plan-task", "execute-task", "verify") */
  unitType: string
  /** Unique unit identifier (e.g. "wave-2/task-3") */
  unitId: string
  /** Model used (e.g. "claude-opus-4-6") */
  model: string
  /** ISO timestamp of start */
  startedAt: string
  /** ISO timestamp of finish */
  finishedAt: string
  /** Token breakdown */
  tokens: {
    input: number
    output: number
    cacheRead: number
    cacheWrite: number
    total: number
  }
  /** Cost in USD */
  costUsd: number
  /** Number of tool calls made */
  toolCalls: number
  /** Pipeline phase this unit belongs to */
  phase: MetricsPhase
}

/** Persistent ledger of all unit metrics for a project */
export interface MetricsLedger {
  /** Schema version */
  version: 1
  /** ISO timestamp of project start */
  projectStartedAt: string
  /** All recorded unit metrics */
  units: UnitMetrics[]
}

// ---------------------------------------------------------------------------
// Requirement Quality — "unit tests for English" (Concept 6.3)
// ---------------------------------------------------------------------------

/** Dimensions for evaluating requirement quality */
export type QualityDimension =
  | 'COMPLETENESS' | 'CLARITY' | 'CONSISTENCY'
  | 'MEASURABILITY' | 'COVERAGE' | 'TESTABILITY'

/** A single item in a requirement quality checklist */
export interface RequirementCheckItem {
  /** Item identifier (CHK-001) */
  id: string
  /** The question being evaluated */
  question: string
  /** Quality dimension this item measures */
  dimension: QualityDimension
  /** Reference to the spec section (null = no traceability) */
  specReference: string | null
  /** Evaluation result */
  status: 'pass' | 'fail' | 'na'
  /** Evaluator notes */
  notes: string | null
}

/** Complete requirement quality checklist for a spec */
export interface RequirementChecklist {
  /** Spec being evaluated */
  specId: string
  /** All checklist items */
  items: RequirementCheckItem[]
  /** % of items with specReference (0-1) */
  traceabilityRate: number
  /** % of items with status='pass' (0-1) */
  passRate: number
}

// ---------------------------------------------------------------------------
// Distillate — lossless document compression (Concept 10.1)
// ---------------------------------------------------------------------------

/** Configuration for a distillation run */
export interface DistillateConfig {
  /** Source file paths to distill */
  sourcePaths: string[]
  /** What the distillate will be used for (e.g. "plan creation") */
  downstreamConsumer?: string | undefined
  /** Target token budget */
  tokenBudget?: number | undefined
  /** Custom output path */
  outputPath?: string | undefined
  /** Run round-trip validation */
  validate?: boolean | undefined
}

/** Result of a distillation run */
export interface DistillateResult {
  /** The distilled content */
  content: string
  /** Headings preserved from source */
  sourceHeadings: string[]
  /** Named entities preserved from source */
  namedEntities: string[]
  /** Estimated token count of the distillate */
  tokenEstimate: number
  /** Compression ratio (distilled/original, e.g. 0.35 = 65% reduction) */
  compressionRatio: number
}

// ---------------------------------------------------------------------------
// Compression Rules — reusable strip/preserve/transform (Concept 10.6)
// ---------------------------------------------------------------------------

/** What a compression rule does to matching content */
export type CompressionAction = 'strip' | 'preserve' | 'transform'

/** A single reusable compression rule */
export interface CompressionRule {
  /** Rule identifier */
  id: string
  /** What to do with matching content */
  action: CompressionAction
  /** Regex pattern to match */
  pattern: string
  /** Human-readable description */
  description: string
  /** Replacement text (for 'transform' action) */
  replacement?: string | undefined
}

// ---------------------------------------------------------------------------
// TDD Enforcer — RED-GREEN-REFACTOR cycle (Concept 3.3)
// ---------------------------------------------------------------------------

/** TDD cycle phases */
export type TddPhase = 'RED' | 'GREEN' | 'REFACTOR'

/** Result of running tests during a TDD cycle */
export interface TestRunResult {
  phase: TddPhase
  exitCode: number
  failureCount: number
  timestamp: string
}

/** State of a TDD enforcement cycle for a task */
export interface TddCycleState {
  taskId: string
  phase: TddPhase
  testFilePath: string | null
  testRunResults: TestRunResult[]
  productionFilesModified: string[]
}

// ---------------------------------------------------------------------------
// Self-Critique — mandatory self-assessment gates (Concept 8.1)
// ---------------------------------------------------------------------------

/** A predicted issue from self-critique */
export interface PredictedIssue {
  description: string
  severity: 'high' | 'medium' | 'low'
  mitigated: boolean
  mitigation: string | null
}

/** Self-critique report produced at post-code and post-test gates */
export interface SelfCritiqueReport {
  taskId: string
  gate: 'post-code' | 'post-test'
  predictedBugs: PredictedIssue[]
  edgeCases: PredictedIssue[]
  overallPass: boolean
  skipped: boolean
  timestamp: string
}

// ---------------------------------------------------------------------------
// Adversarial Review — cynical posture, minimum findings (Concept 10.2)
// ---------------------------------------------------------------------------

/** Configuration for an adversarial review */
export interface AdversarialReviewConfig {
  content: string
  contentType: 'spec' | 'plan' | 'code' | 'diff' | 'architecture'
  minimumFindings: number
}

/** A single finding from adversarial review */
export interface AdversarialFinding {
  description: string
  severity: 'critical' | 'high' | 'medium' | 'low'
  category: 'missing' | 'wrong' | 'vague' | 'inconsistent' | 'security' | 'performance'
  evidence: string
}

/** Result of an adversarial review */
export interface AdversarialReviewResult {
  findings: AdversarialFinding[]
  suspicious: boolean
  reviewerPosture: string
}

// ---------------------------------------------------------------------------
// Edge Case Hunter — exhaustive path enumeration (Concept 10.3)
// ---------------------------------------------------------------------------

/** A single edge case finding */
export interface EdgeCaseFinding {
  location: string
  triggerCondition: string
  guardSnippet: string
  potentialConsequence: string
  severity: 'high' | 'medium' | 'low'
}

/** Result of edge case hunting */
export interface EdgeCaseHuntResult {
  findings: EdgeCaseFinding[]
}

// ---------------------------------------------------------------------------
// Session Forensics — crash recovery traces (Concept 12.2)
// ---------------------------------------------------------------------------

/** A traced tool call from the audit log */
export interface TracedToolCall {
  name: string
  input: Record<string, unknown>
  result?: string | undefined
  isError: boolean
}

/** Complete execution trace reconstructed from a crashed session */
export interface ExecutionTrace {
  toolCalls: TracedToolCall[]
  filesWritten: string[]
  filesRead: string[]
  commandsRun: string[]
  errors: string[]
  lastReasoning: string
  toolCallCount: number
}

/** Recovery briefing injected into recovery session prompt */
export interface RecoveryBriefing {
  unitType: string
  unitId: string
  trace: ExecutionTrace
  gitChanges: string | null
  prompt: string
}

// ---------------------------------------------------------------------------
// Approval Gates — formal human governance (Concept 14.3)
// ---------------------------------------------------------------------------

/** Types of approvals in the pipeline */
export type ApprovalType =
  | 'SPEC_APPROVAL'
  | 'PLAN_APPROVAL'
  | 'ARCHITECTURE_DECISION'
  | 'BUDGET_INCREASE'
  | 'CONSTITUTION_CHANGE'
  | 'RISK_ACCEPTANCE'

/** Status of an approval request */
export type ApprovalStatus = 'pending' | 'approved' | 'rejected' | 'revision_requested'

/** A formal approval request */
export interface ApprovalRequest {
  id: string
  type: ApprovalType
  description: string
  requestedAt: string
  status: ApprovalStatus
  decidedAt: string | null
  decisionNote: string | null
  artifacts: string[]
}

// ---------------------------------------------------------------------------
// Research Phase — resolve technical unknowns (Concept 6.4)
// ---------------------------------------------------------------------------

/** A technical unknown blocking or informing planning */
export interface TechnicalUnknown {
  id: string
  description: string
  source: string
  priority: 'blocking' | 'informational'
  status: 'unresolved' | 'resolved'
}

/** A research finding resolving an unknown */
export interface ResearchFinding {
  unknownId: string
  finding: string
  sources: string[]
  recommendation: string
  confidence: 'high' | 'medium' | 'low'
}

/** State of a research phase */
export interface ResearchPhaseState {
  unknowns: TechnicalUnknown[]
  findings: ResearchFinding[]
  status: 'pending' | 'complete'
}

// ---------------------------------------------------------------------------
// Experiment Loop — autonomous metric optimization (Concept 4.1)
// ---------------------------------------------------------------------------

/** Result of a single experiment iteration */
export interface ExperimentResult {
  commitHash: string
  metric: number
  status: 'keep' | 'discard' | 'crash'
  description: string
  timestamp: string
}

/** State of an experiment loop */
export interface ExperimentLoopState {
  tag: string
  branch: string
  baseline: number | null
  experiments: ExperimentResult[]
  stopCondition: 'manual' | 'budget' | 'plateau'
}

// ---------------------------------------------------------------------------
// Constitution Semantic Versioning (Concept 6.5)
// ---------------------------------------------------------------------------

/** Semantic version for constitution changes */
export interface ConstitutionVersion {
  major: number
  minor: number
  patch: number
}

/** Classification of a constitution change */
export interface ConstitutionVersionChange {
  type: 'added' | 'removed' | 'modified' | 'clarified'
  principle: string
  impact: 'breaking' | 'additive' | 'cosmetic'
  affectedArtifacts: string[]
}

/** Impact report for constitution version change */
export interface SyncImpactReport {
  version: ConstitutionVersion
  changes: ConstitutionVersionChange[]
  affectedSpecs: string[]
  affectedPlans: string[]
  migrationRequired: boolean
}

// ---------------------------------------------------------------------------
// Dispatch Guard — prerequisite verification (Concept 12.5)
// ---------------------------------------------------------------------------

/** Result of a dispatch guard check */
export interface DispatchGuardResult {
  allowed: boolean
  blockedBy: string[]
  missingPrerequisites: string[]
}

// ---------------------------------------------------------------------------
// Constitution types — canonical definitions used by enforcer + orchestrator
// ---------------------------------------------------------------------------

/** A parsed constitution principle */
export interface ConstitutionPrinciple {
  /** The section this principle belongs to */
  section: string
  /** The principle name/text */
  name: string
}

/** A detected constitution violation */
export interface ConstitutionViolation {
  /** The principle that was violated */
  principle: string
  /** The content that triggered the violation */
  trigger: string
}

/** Result of enforcing constitution against output */
export interface EnforcementResult {
  /** List of violations found */
  violations: ConstitutionViolation[]
  /** Whether any violations were found */
  hasViolations: boolean
}
