// Task Dispatch Payload — FR-302
// Contracts are stubs in Alpha — shapes stable from commit one

/** Payload dispatched to isolated subagents via Task() */
export interface TaskDispatchPayload {
  /** Unique task identifier within the session */
  taskId: string
  /** Type of task being dispatched */
  type: 'specify' | 'plan' | 'execute' | 'verify' | 'quick' | 'optimize'
  /** The specific plan or spec content for this task */
  content: string
  /** Task-specific context (codebase snippets, prior outputs) */
  context?: string
  /** Target output path for generated artifacts */
  outputPath?: string
  /** Budget constraint for this task in USD */
  budgetUsd?: number
  /** Path to the project constitution file, if it exists (FR-202) */
  constitutionPath?: string
}

/** Result returned by a completed subagent task */
export interface TaskResult {
  taskId: string
  success: boolean
  /** Artifacts generated by the task (file paths) */
  artifacts: string[]
  /** Token usage for cost tracking */
  tokensUsed?: number
  /** Estimated cost in USD */
  costUsd?: number
  /** Error details if task failed */
  error?: string
  /** Response content from the subagent */
  response?: string
}
